### ISSUE TITLE
More than one client url

### ISSUE THREAD

**Issue by RicardoRB** [graphql-java-kickstart/graphql-spring-webclient#24]
**Is your feature request related to a problem? Please describe.**
At the moment it is just possible to have one URL client

```yaml
graphql:
  client:
    url: https://graphql.github.com/graphql
```

**Describe the solution you'd like**
Define by application.yml your own URLs

```yaml
app:
  graphql:
    one-client:
      url: https://graphql.github.com/graphql
   two-client:
      url: https://graphql.github.com/graphqltwo
```

**Describe alternatives you've considered**

Using RestTemplate you can define URL as you want

```java
restTemplate.postForObject(url, httpEntity, ResponseDto.class)
```

**Additional context**
